export const SWIPER = {
  NORMAL_DELAY: 4000,
  INFINITE_DELAY: 86400000, // 1 day
  SPACE_BETWEEN: -70,
  SLIDES_PER_VIEW: 1,
  LOOPED_SLIDES: 2,
  LAZY_LOADED_PREV_NEXT: 1,
};
export const STANDARD = {
  WIDTH: 390,
};
